apiVersion: apps/v1
kind: Deployment
metadata:
  name: Cheese-Rat-Cheese
  labels:
    app: Cheese-Rat-Cheese
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Cheese-Rat-Cheese
  template:
    metadata:
      labels:
        app: Cheese-Rat-Cheese
    spec:
      containers:
      - name: Cheese-Rat-Cheese
        image: ghcr.io/cool129/cheese-rat-cheese-cicd:sha-cee5feed08fcf1f24f417e6660c4f0bee7c7204d
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: github-container-registry